language: python
python:
  - "3.9"
os:
  - linux

git:
  depth: 1

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink
  - PLATFORMIO_PROJECT_DIR=examples/arduino-ble-led
  - PLATFORMIO_PROJECT_DIR=examples/arduino-serial-plotter

install:
  - pip install platformio
    pio update
  - pio platform install https://github.com/OS-Q/P41/archive/pio.zip

script:
  - pio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
