build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-ble-led"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-serial-plotter"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-bluefruit-bleuart"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-nina-b1-generic-example"

platform:
  - x64
install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\Python37\Scripts;%PATH%
  - cmd: pip3 install platformio
  - cmd: pio update
  - cmd: pio platform install file://.

test_script:
  - cmd: pio run -d %PLATFORMIO_PROJECT_DIR%
