build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-ble-led"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-bluefruit-bleuart"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-serial-plotter"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-ble-thermometer"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-dsp"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-events"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-nfc"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-rtos"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-serial"
    - PLATFORMIO_PROJECT_DIR: "examples/zephyr-ble-beacon"
    - PLATFORMIO_PROJECT_DIR: "examples/zephyr-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/zephyr-subsys-nvs"

install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\Python36\Scripts;%PATH%
  - cmd: pip3 install -U https://github.com/OS-Q/S03/archive/master.zip
  - cmd: platformio platform install file://.

test_script:
  - cmd: platformio run -s -d %PLATFORMIO_PROJECT_DIR%
