version: 2
jobs:

  QIO:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "Install"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
            python -m pip install --upgrade pip
            pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
            qio platform install file://.
      - run:
          name: "Build"
          command: |
            pio run -d examples/arduino-blink
            pio run -d examples/arduino-ble-led
            pio run -d examples/arduino-serial-plotter
            pio run -d examples/arduino-nina-b1-generic-example
            pio run -d examples/mbed-rtos-ble-thermometer
            pio run -d examples/mbed-rtos-blink-baremetal
            pio run -d examples/mbed-rtos-nfc
            pio run -d examples/mbed-nfc

  PIO:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "Install"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
            python -m pip install --upgrade pip
            pip install -U https://github.com/platformio/platformio/archive/develop.zip
            pio platform install file://.
      - run:
          name: "Build"
          command: |
            pio run -d examples/arduino-blink
            pio run -d examples/arduino-ble-led
            pio run -d examples/arduino-serial-plotter
            pio run -d examples/arduino-nina-b1-generic-example
            pio run -d examples/mbed-rtos-ble-thermometer
            pio run -d examples/mbed-rtos-blink-baremetal
            pio run -d examples/mbed-rtos-nfc
            pio run -d examples/mbed-nfc

workflows:
    version: 2
    run_ci:
        jobs:
          - QIO
          - PIO

